version: '3.9'
services:
  backend:
    build:
      # context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/scr/app/node_modules
    # env_file:
    #   - ./.env
    # ports:
    #   - 8080:8080
    environment:
      - NODE_ENV=development
    command: yarn dev
    # depends_on:
    #   - mongodb
#   mongodb:
#     image: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USER
#       MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PASSWORD
#     volumes:
#       - mongo-db:/data/db

# volumes:
#   mongo-db: {}
