version: '3.9'
services:
  backend:
    build:
      context: .
      # target: development
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/scr/app/node_modules
    restart: always
    networks:
      - app-network
    env_file:
      - ./.env
    # ports:
    #   - 80:$PORT
    # environment:
    #   - NODE_ENV=development
    # command: yarn dev
    depends_on:
      - mongodb
      # - nginx

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - backend
    networks:
      - app-network
    # environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email abbaslamouri@yrlus.com --agree-tos --no-eff-email --staging -d lightmylamp.com  -d www.lightmylamp.com

  mongoDb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PASSWORD
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: {}
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
