version: '3.9'
services:
  backend:
    build:
      # context: .
      target: production
    # env_file:
    #   - ./.env
    # ports:
    #   - 8080:8080
    environment:
      - NODE_ENV=production
